# Data Files, NumPy & Pandas

Basic (text) file handling, *NumPy*, *pandas*, and *DateTime*. For interactive reading and executing code blocks [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/hydro-informatics/jupyter-python-course/main) and find *b06-pynum.ipynb* or {ref}`install-python` locally along with {ref}`jupyter`.

```{admonition} Watch this section in video format
:class: tip, dropdown
<iframe width="701" height="394" src="https://www.youtube-nocookie.com/embed/fEYXfwvQfmo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>Watch this section as a video on the <a href="https://www.youtube.com/@hydroinformatics">@hydroinformatics channel on YouTube</a>.</p>
```

# Load and Write Basic Data Files

Data can be stored in many different (text) file formats such as *txt* or *csv* files. Python provides the `open(file)` and `write(...)` functions to read and write data from nearly every text file format. In addition, there are packages such as `csv` (for *csv* files), which simplify handling specific file types. The following sections illustrate the use of the `open(file)` and `write(...)` functions. The later shown *pandas* module provides more functions to import and export numeric data along with row and column headers.

(open-modes)=
## Load (Open) Text File Data 

The `open` command loads text files as file object in Python. The syntax of the `open` command is: 

```python
open("file-name", "mode")
```

where:

* `file-name` is the file to open (e.g., `"data.txt"`); if the file is not in the script directory, the *filename* needs to be extended by the full directory (path) to the data file (e.g., `"C:/experiment1/data.txt"`).
* `mode` defines the access type and it can take the following values:
    - `"r"` - read-only (default value if no `"mode"` value is provided); the file cannot be modified nor overwritten.
    - `"rb"` - read-only in binary format; the binary format is advantageous if the file is not a text file but media such as pictures or videos.
    - `"r+"` - read and write.
    - `"w"` - write-only; a new file is created if a file with the provided `file-name` does not yet exist.
    - `"wb"` - write-only in binary mode.
    - `"w+"` - create, write and read.
    - `"wb+"` - write and read in binary mode.
    - `"a"` - append new data to a file; the write-pointer is placed at the end of the file and a new file is created if a file with the provided `file name` does not yet exist.
    - `"ab"` - append new data in binary mode.
    - `"a+"` - both append (write at the end) and read.
    - `"ab+"` - append and read data in binary mode.

When `"r"` or `"w"` modes are used, the file pointer (i.e, the blinking cursor that you can see, for example, in Word documents) is placed at the beginning of the file. For `"a"` modes, the file pointer is placed at the end of the file.

It is good practice to read and write data from and to a file within a `with` statement to avoid file lock issues. For example, the following code block creates a new text file within a `with` statement:

In [1]:
with open("data/new.csv", mode="w+") as file:
    file.write("And yet it moves.")

(read)=
## Read-only

Once the file object is created, we can parse the file and copy the file data content to a desired Python {ref}`data type <var>` (e.g., a list, tuple or dictionary). Parsing the data works with {ref}`for-loops <for>` (other loop types will also work) to iterate on lines and line entries. The lines represent *strings* and data columns can be separated by using the built-in *string* function `line_as_list = str().split("SEPARATOR")`, where `"SEPARATOR"` can be `","` (comma), `";"` (semicolon), `"\t"` (tab), or any other sign. After reading all data from a file, use `file_object.close()` to avoid that the file is locked by Python and cannot be opened by another program.

The following example opens a text file called *pure-numbers.txt* ([download pure-numbers.txt](https://raw.githubusercontent.com/hydro-informatics/jupyter-python-course/main/data/pure-numbers.txt) into a local sub-folder called *data*) that contains *float* numbers between 0.0 and 10.0. The file has 17 data rows (e.g., for 17 experimental runs) and 4 data columns (e.g., for 4 measurements per experimental run), which are separated by a *TAB* (`"\t"` separator). The below code block uses the built-in function `readlines()` to parse the file lines, splits the lines using the `"\t"` separator, and loops over the line entries to append them to the list variable `data_list` only if `entry` is numeric (verified with the `try` - `except` statement). `data_list` is a nested list that is initiated at the beginning of the script and a sub-list (nested list) is appended for every file line (row).

In [2]:
file_object = open("data/pure-numbers.txt")  # read file with default "mode"="r"

data_list = []  # this will be a nested list with 17 sub-lists (rows) containing 4 entries (columns)=

for line in file_object.readlines():
    line_as_list = line.split("\t")  # converts the line into a list using a tab (\t) separator
    data_list.append([])  # append an empty sub-list for every file line (17 rows)
    for entry in line_as_list:
        try:
            # try to append the entry as floating point number to the last sub-list, which is pointed at using [-1]
            data_list[-1].append(float(entry))
        except ValueError:
            # if entry is not numeric, append 0.0 to the sub-list and print a warning message
            print("Warning: %s is not a number. Replacing value with 0.0." % str(entry))

# verify that data_list contains the 17 rows (sub-lists) with the built-in list function __len__()
print("Number of rows: %d" % len(data_list)) 

# verify that the first sub-list has four entries (number of columns)
print("Number of columns: %d" % len(data_list[0]))

file_object.close()  # close file (otherwise it will be locked as long as Python is still running!) alternative: use with-statement
print(data_list)  # print the data

Number of rows: 17
Number of columns: 4
[[2.202, 3.658, 0.201, 1.651], [0.904, 0.643, 1.094, 1.859], [2.104, 2.786, 2.212, 3.489], [1.181, 4.415, 0.331, 3.418], [2.203, 2.882, 0.874, 1.151], [4.044, 4.848, 1.704, 3.523], [4.407, 4.494, 0.608, 0.387], [1.015, 4.415, 0.672, 2.221], [4.798, 2.759, 3.521, 1.714], [3.495, 4.206, 0.288, 3.801], [4.947, 3.791, 1.546, 3.989], [0.695, 2.35, 4.561, 1.609], [1.581, 0.824, 0.293, 3.458], [1.216, 1.475, 2.56, 0.456], [2.956, 0.904, 3.029, 3.559], [0.691, 2.187, 3.533, 2.188], [0.44, 2.772, 3.386, 2.671]]


```{tip}
Recall the `with` statement from the above example. With the `with` statement, we do not have to write `file.close()`.
```

(create)=
## Create and Write Files 

A file is created with the `"w"` or `"a"` modes (e.g., `open(file_name, mode="a")`).

```{tip}
When `mode="w"`, the provided file is opened with the pointer at position zero. Writing data will make the pointer overwrite any existing data at the position. That means any existing data in the opened file will be overwritten. To avoid overwriting data in an existing file use `mode="a"`.
```

Imagine that the loaded `data_list` contains measurements in mm. For each value in each sub-list, append the string `"nan"` to `new_data_list` if the value is less than or equal to 1.0; otherwise, preserve the original numeric value. If indices are used explicitly, access a nested-list value as `data_list[i][j]`.
Use a `with` statement and context manager to ensure that the file is closed automatically after the block finishes.

In [3]:
# create a new list and overwrite all values <= 1.0 with nan
new_data_list = []  
for i in data_list:
    new_data_list.append([])
    for j in i:
        if j <= 1.0:
            new_data_list[-1].append("nan")
        else:
            new_data_list[-1].append(j)

print(new_data_list)
# write the modified new_data_list to a new text file
new_file = open("data/modified-data.csv", mode="w+")  # lets just use csv: Python does not care about the file ending (could also be file.wayne)
for row in new_data_list:
    new_line = ", ".join([str(e) for e in row]) + "\n"
    new_file.write(new_line)
new_file.close()


[[2.202, 3.658, 'nan', 1.651], ['nan', 'nan', 1.094, 1.859], [2.104, 2.786, 2.212, 3.489], [1.181, 4.415, 'nan', 3.418], [2.203, 2.882, 'nan', 1.151], [4.044, 4.848, 1.704, 3.523], [4.407, 4.494, 'nan', 'nan'], [1.015, 4.415, 'nan', 2.221], [4.798, 2.759, 3.521, 1.714], [3.495, 4.206, 'nan', 3.801], [4.947, 3.791, 1.546, 3.989], ['nan', 2.35, 4.561, 1.609], [1.581, 'nan', 'nan', 3.458], [1.216, 1.475, 2.56, 'nan'], [2.956, 'nan', 3.029, 3.559], ['nan', 2.187, 3.533, 2.188], ['nan', 2.772, 3.386, 2.671]]


## Modify Existing Files

Existing text files can be opened and modified in either `mode="r+"` (pretending that information needs to be read before it is modified) or `mode="a+"`. Recall that `"r+"` will place the pointer at the beginning of the file and `"a+"` will place the pointer at the end of the file. Thus, if we want to modify lines or entries of an existing file, `"r+"` is the good choice and if we want to append data at the end of the file, `"a"` is the good choice (`+` is not strictly needed in the case of `"a"`). This section shows two examples: (1) modification of existing data in a file using `"r+"`, and (2) appending data to an existing file using `"a"`.

Example 1 - Replace data in an existing file with `"r+"`
: In the previous code block, we eliminated all measurements that were smaller than 1 *mm* because of the precision of the measurement device. However, we have retained all other values with two-digit accuracy - an accuracy that is not given. Consequently, all decimal places in the measurements must also be eliminated. To achieve this, we have to round all measured values with Python's built-in round function (`round(number, n-digits)`) to zero decimal places (i.e., `n-digits = 0`).
  In this example (featured in the below code block), an exception `IOError` is raised when the file `"data/modified-data.csv"` does not exist (or if it is locked by another software). An `if` statement ensures that rounding the data is only attempted if the file exists.
  The overwriting procedure first reads all lines of the file into the `lines` variable. After reading all lines, the pointer is at the end of the file, and `file.seek(0)` puts the pointer back to position 0 (i.e., at the beginning of the file). `file.truncate()` purges the file. Thus, the original file is blank for a moment and all file contents are stored in the `lines` variable. Rounding the data happens within a *for-loop* that:

    * Splits the comma-separated line *string* (produces `lines_as_list`).
    * Creates the temporary list `_numeric_line_`, where rounded, numeric values are stored (the variable is overwritten in every iteration).
    * Loops over the line entries (`line_as_list`), where an exception statement appends rounded (to zero digits), numeric values and appends `"nan"` when an entry is not numeric.
    * Writes the modified line to the `"data/modified-data.csv"` *csv* file.

  Finally, the *csv* is closed with `modified_file.close()`.

In [4]:
try:
  with open("data/modified-data.csv", mode="r+") as modified_file:
	  lines = modified_file.readlines()
	  modified_file.seek(0)
	  modified_file.truncate()

	  for line in lines:
		  line_as_list = line.split(", ")
		  numeric_line = []
		  for entry in line_as_list:
			  try:
				  numeric_line.append(round(float(entry), 0))
			  except ValueError:
				  numeric_line.append(entry.strip())
		  modified_file.write(", ".join(str(entry) for entry in numeric_line) + "\n")
  print("Processed file.")
except OSError as error:
  print(f"Could not process the file: {error}")

Processed file.


Theoretically the above code snippet can be re-written as a function to modify any data in a file. In addition, other threshold values or particular data ranges can be filtered using `if` - `else` statements.

Example 2 - Append data to an existing file with `"a+"`
: By coincidence, you find a hand-written measurement protocol that has data of an 18th experimental run, which is not in the electronic measurement data file due to a data transmission error. Now, you want to add the data to the above-produced *csv* file. Entering the data does not take much work, because only 4 measurements were performed per experimental run and the below code block contains the hand-written data in a list variable called `forgotten_data`.
  This example uses the `os` module (recall {ref}`sec-pypckg`) to verify if the data file exists with `os.path.isfile()` (the `os.getcwd()` statement is a gadget here). The code block features the usage of a `with` statement (i.e., a `with` - context manager or name space). 

  The essential part of the code that writes the line to the data file is `file.write(line)`, where `line` corresponds to the above-introduced `", ".join(list-of-strings) + "\n"` *string*.

In [5]:
import os
print(os.getcwd())
forgotten_data = [4.0, 3.0, "nan", 8.0]

if os.path.isfile("data/modified-data.csv"):
    with open("data/modified-data.csv", mode="a") as file_object:
        file_object.write(", ".join([str(e) for e in forgotten_data]) + "\n")
    print("Data appended.")
else:
    print("The file does not exist.")

/home/schwindt/github/hyhome-v2/jupyter
Data appended.


```{admonition} Challenge
The expression `", ".join([str(e) for e in a_list]) + '\n'` is a recurring expression in many of the above-shown code blocks. How does a function look like that automatically generates this expression for lists of different data types?
```

(numpy)=
# NumPy 

*NumPy* provides high-level mathematical functions for linear algebra including operations on multi-dimensional arrays and matrices. The open-source *NumPy* (for *Numerical Python*) library is written in Python and [C](https://en.wikipedia.org/wiki/C_(programming_language)), and comes with comprehensive documentation ([download the latest version on the developer's web site](https://numpy.org/doc/) or [read the developer's online tutorial](https://numpy.org/devdocs/user/quickstart.html)).

```{admonition} Watch the NumPy section in video format
:class: tip, dropdown
<iframe width="701" height="394" src="https://www.youtube-nocookie.com/embed/P2t0z-t-l7w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>Watch this section as a video on the <a href="https://www.youtube.com/@hydroinformatics">@hydroinformatics channel on YouTube</a>.</p>
```

## Installation

*NumPy* can be installed through *Anaconda* ({ref}`recall instructions <install-pckg>`) and the developers recommend using a scientific Python distribution (*Anaconda*) with [*SciPy Stack*](https://scipy.org/install/).

The provided *Anaconda* [environment.yml (`flussenv`)](https://raw.githubusercontent.com/Ecohydraulics/flusstools-pckg/main/environment.yml) already includes *NumPy* (more information in the {ref}`installation <conda-env>` section). Similarly, Linux users will have *NumPy* installed in a virtual environment (e.g., `vflussenv`) with *pip* (recall {ref}`pip-installing flusstools <pip-quick>`). Otherwise, to install *NumPy* in any other *conda* environment, open *Anaconda Prompt* (*Start* > type *Anaconda Prompt*) and type:

```python
conda activate ENVIRONMENT-NAME
conda install numpy
```

To pip-install *NumPy* in any other virtual environment tap:

```python
pip install numpy
```

## Usage

The NumPy library is typically imported with `import numpy as np`. Create a NumPy array with `np.array(values)`, where `values` is array-like input such as a list or tuple. Nested sequences can be used to create multidimensional arrays; for example, `np.array([[1, 2, 3], [4, 5, 6]])` creates an array with two rows and three columns.

```{tip}
This section provides insights into basic *NumPy* functions and it does not (rather: cannot) cover all *NumPy* functions and data types. Generally speaking, be sure that whatever mathematical operation you want to perform, *NumPy* offers a solution. Check out the [*NumPy* documentation](https://numpy.org/devdocs/user/quickstart.html), [have a look at *NumPy*'s built-in functions and methods overview](https://numpy.org/devdocs/user/quickstart.html#functions-and-methods-overview), or use your favorite search engine with the search words **numpy** ***FUNCTION***.
```

The following code block shows very basic usage of *NumPy* (or: numpy) imported as `np` and the creation of a *2x3* numpy array. The rounded parentheses indicated that the value sequence of the `np.array` represents a tuple for creating a multi-dimensional array.

In [6]:
import numpy as np
an_array = np.array(([2, 3, 1], [4, 5, 6]))
print(an_array)

[[2 3 1]
 [4 5 6]]


*NumPy* arrays (data type: *ndarray*) have many built-in features, for example to output the array size:

In [7]:
print(type(an_array))
print("Array dimensions: " + str(an_array.shape))
print("Total number of array elements: " + str(an_array.size))
print("Number of array axes: " + str(an_array.ndim))

<class 'numpy.ndarray'>
Array dimensions: (2, 3)
Total number of array elements: 6
Number of array axes: 2


There are many types of `np.array`s and many ways to create them:

In [8]:
print(np.array([(2, 3, 1), (4, 5, 6)]))  # the same as an_array
print(np.array([[2, 3, 1], [4, 5, 6]], dtype=complex))

[[2 3 1]
 [4 5 6]]
[[2.+0.j 3.+0.j 1.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


Arrays of zeros or ones or empty arrays can be created with *integer* or *float* data types. When creating such arrays, be aware of using tuples (i.e., sequences embraced with rounded parentheses) to define array dimensions:

In [9]:
print(np.zeros((2,6)))
print(np.ones((2,6), dtype=np.float64))  # other dtypes: int16, np.int16, float, np.float32, np.complex64
print(np.empty((2,6)))
print(np.empty((2,6), dtype=np.int16))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[19880 11437     6     0     0     0]
 [    0     0     0     0     0     0]]


`np.empty(shape)` allocates an array without initializing its entries. Any displayed values are arbitrary remnants of memory and may differ between runs. Fill every entry before reading or using the array; use `np.zeros(shape)` or `np.ones(shape)` when initialized values are required.

```{admonition} Data type sizes
:class: note
*NumPy* data types have different sizes (in [bytes](https://en.wikipedia.org/wiki/Byte)) and the more digits, the larger the variable size. For example, `np.float64` has an item size of 8 bytes (64/8), while `np.float32` has an item size of 4 bytes (32/8) only. Use `ndarray.itemsize` (e.g., `an_array.itemsize`) to find out the size of an array in bytes. For analyses of large datasets, the data type gets very important regarding computation speed and storage.
```

*NumPy* provides the `arange(start, end, step-size)` function to create numeric sequences. Such sequences represent arrays (`ndarray`) that can later be reshaped (i.e., re-organized in columns and rows). 

In [10]:
print("1D array:")
print(np.arange(0, 10, 2))  # 1D array
print("\n2D array:")
print(np.arange(0, 12, 2).reshape(2, 3))  # 2D array
print("\n3D array:")
print(np.arange(1, 13, 1).reshape(2, 2, 3))  # 3D array
print("\n1D Linspace (start, end, number-of-elements):")
print(np.linspace(0, np.pi, 3))

1D array:
[0 2 4 6 8]

2D array:
[[ 0  2  4]
 [ 6  8 10]]

3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1D Linspace (start, end, number-of-elements):
[0.         1.57079633 3.14159265]


Random numbers can be generated with *NumPy*'s random number generator `np.random` and its `.random(range_tuple)` function.

In [11]:
rand_array = np.random.random((2,4))
print(rand_array)

[[0.78599116 0.11777177 0.29913723 0.9290063 ]
 [0.70878365 0.5521523  0.81552564 0.17867719]]


Built-in array functions enable finding minimum or maximum values, or sums of arrays:

In [12]:
print("Sum of 12-elements ones-array: " + str(np.ones((2,6)).sum()))
print("Minimum: " + str(an_array.min()))
print("Maximum: " + str(an_array.max()))

Sum of 12-elements ones-array: 12.0
Minimum: 1
Maximum: 6


(colors)=
## Color Arrays 

Arrays may also contain color information, where colors represent a mix of the three base colors red, green, and blue (**RGB**). Thus, one color can be defined as `[red-value, green-value, blue-value]`, and a value of `0` means that a color tone is not present, while `255` is its **maximum** value. There is no color when all color tone values are zero, which corresponds to *black*; when all color tones are maximum (255), the color mix corresponds to *white*. This way, array elements can be lists of color tones, and plotting such arrays produces images. The following example produces an array with 5 color-list elements, which could be plotted as a very basic image with 5 pixels (one black, red, green, blue, and white, respectively):

In [13]:
color_set = np.array([[0, 0, 0],         # black
                      [255, 0, 0],       # red
                      [0, 255, 0],       # green
                      [0, 0, 255],       # blue
                      [255, 255, 255]])  # white

(array-matrix-operations)=
## Array (Matrix) Operations

Array calculations (matrix operations) follow the rules of linear algebra:

In [14]:
A = np.random.random((2,4))
B = np.random.random((4,2))
print("Subtraction: " + str(A.transpose() - B))
print("Element-wise product: " + str(A.transpose() * B))
print("Matrix product (option 1): " + str(A @ B))
print("Matrix product (option 2): " + str(A.dot(B)))

Subtraction: [[ 0.39513798  0.92256882]
 [ 0.34627686 -0.64066838]
 [-0.41525172  0.49672182]
 [-0.64648598  0.21224637]]
Element-wise product: [[0.02631898 0.05370238]
 [0.2312502  0.07207233]
 [0.28977301 0.14078519]
 [0.10386917 0.18425933]]
Matrix product (option 1): [[0.65121136 0.64929413]
 [1.06516605 0.45081924]]
Matrix product (option 2): [[0.65121136 0.64929413]
 [1.06516605 0.45081924]]


Further element-wise calculations include exponential (`**`), geometric (`np.sin`, `np.cos`, `np.tan`, etc.), and boolean operators:

In [15]:
print("A to the power of 3: " + str(A**3))
print("Exponential: " + str(np.exp(A)))
print("Square root: " + str(np.sqrt(A)))
print("Sine of A times 3: " + str(np.sin(A) * 3))
print("Boolean where A is smaller than 0.3: " + str(A < 0.3))

A to the power of 3: [[9.30892075e-02 3.20353634e-01 5.03795493e-02 2.36414082e-03]
 [9.34027227e-01 9.30307166e-04 3.40544706e-01 1.64838161e-01]]
Exponential: [[1.57335504 1.9822692  1.44676927 1.14249724]
 [2.65782184 1.10254456 2.01038396 1.73031119]]
Square root: [[0.67320896 0.82718937 0.60772772 0.36498826]
 [0.9886895  0.31244319 0.83565886 0.74047368]]
Sine of A times 3: [[1.313562   1.89625803 1.08298042 0.39846826]
 [2.48731829 0.29239731 1.9288087  1.56371481]]
Boolean where A is smaller than 0.3: [[False False False  True]
 [False  True False False]]


## Array Shape Manipulation

Sometimes it is necessary to stack a multi-dimensional array into a vector or recast the shape of an array. Beyond the `reshape()` function, there are a couple of other options to manipulate the shape of an array:

In [16]:
print("Flattened matrix A (into a vector):\n" + str(A.ravel()))
print("\nTranspose matrix A and append B:\n" + str(np.array([A.transpose(), B])))
print("\nTranspose matrix A and append B and cast into a (4x4) array:\n" + str(np.array([A.transpose(), B]).reshape(4,4)))

Flattened matrix A (into a vector):
[0.45321031 0.68424225 0.36933298 0.13321643 0.97750693 0.09762075
 0.69832573 0.54830127]

Transpose matrix A and append B:
[[[0.45321031 0.97750693]
  [0.68424225 0.09762075]
  [0.36933298 0.69832573]
  [0.13321643 0.54830127]]

 [[0.05807233 0.05493811]
  [0.33796539 0.73828912]
  [0.78458471 0.20160391]
  [0.77970241 0.33605491]]]

Transpose matrix A and append B and cast into a (4x4) array:
[[0.45321031 0.97750693 0.68424225 0.09762075]
 [0.36933298 0.69832573 0.13321643 0.54830127]
 [0.05807233 0.05493811 0.33796539 0.73828912]
 [0.78458471 0.20160391 0.77970241 0.33605491]]


## *NumPy* File Handling and `np.nan`

In the above examples on file handling, measurement data were loaded from text files, manipulated (modified), and (re-)written. The data manipulation involved the introduction of `"nan"` (*not-a-number*) values, which were excluded because measurements *<1 mm* were considered errors. Why didn't we use zeros here? Zeros are numbers, too, and have a significant effect on data statistics (e.g., for calculating mean values). However, the `"nan"` *string* value may cause difficulties in data handling, in particular regarding the consistency of function output. *NumPy* provides with the `np.nan` data type a powerful alternative to the tedious `"nan"` *string*.

*NumPy* also has a text file load function called `np.loadtxt(file-name, *args, **kwargs)`, which imports text files as `np.array`s of *float* values. The default *float* value type can be adapted with the optional keyword `dtype`. Other optional keyword arguments are:

* `delimiter=STR` (e.g., `delimiter=';'`), where the default is `"None"`
* `usecols=TUPLE` (e.g., `usecols=(1, 3)` extracts the 2<sup>nd</sup> and 4<sup>th</sup> column), where also one *integer* value is possible to read just on single column
* `skiprows=INT` (e.g., `skiprows=2` skips the first two lines), where the default is `0`
* more arguments are available and listed in the [*NumPy* documentation](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html).

The following example loads the above-created *csv* file *data/modified-data.csv* containing *integer* and `"nan"` *string* values, which are automatically converted to `np.nan`.

In [17]:
experiment_data = np.loadtxt("data/modified-data.csv", delimiter=",")
print("This is the data 4th line (row): " + str(experiment_data[3, :]))
print("The data type of the 3rd (%s) entry is: " % str(experiment_data[3, 2]) + str(type(experiment_data[3, 2])))

This is the data 4th line (row): [ 1.  4. nan  3.]
The data type of the 3rd (nan) entry is: <class 'numpy.float64'>


In addition, or as an alternative, the function `np.load()` picks up data from file-like `.npz`, `.npy`, or pickled (saved Python objects) data sources (more information is available in the [*NumPy* docs](https://numpy.org/doc/stable/reference/generated/numpy.load.html#numpy.load)). 

## Statistics
The above examples featured array functions to assess basic array statistics such as the minimum and maximum. *NumPy* provides many more functions for array statistics such as the mean, median, or standard deviation, including functions that account for `np.nan` values. The following example illustrates some of the statistical functions with the experimental data from the above examples. Note the usage of `nanmean` instead of `mean` and statistics along array axis, where the optional keyword argument `axis=0` corresponds to columns and `axis=1` to statistics along rows in 2-dimensional arrays (maximum axis number corresponds to the array dimensions *n* minus 1, i.e., maximum `axis=n-1`). 

In [18]:
print("Mean value (without nan): " + str(np.mean(experiment_data)))  # no applicable result
print("Mean value with np.nan: " + str(np.nanmean(experiment_data))) 
print("Mean value along axis 0 (columns): " + str(np.nanmean(experiment_data, axis=0))) 
print("Mean value along axis 1 (rows): " + str(np.nanmean(experiment_data, axis=1))) 

Mean value (without nan): nan
Mean value with np.nan: 3.018181818181818
Mean value along axis 0 (columns): [2.78571429 3.26666667 2.9        3.0625    ]
Mean value along axis 1 (rows): [2.66666667 1.5        2.5        2.66666667 2.         3.75
 4.         2.33333333 3.5        3.66666667 3.75       3.
 2.5        1.66666667 3.33333333 2.66666667 3.         5.        ]


The following paragraphs represent a tabular overview of statistical functions in *NumPy* (source: *NumPy* docs). The listed functions only represent the baseline and *NumPy* provides many more options, which can be leveraged using any search engine with *NumPy* and the desired function as a search keyword.

***

Basic statistic functions

| Function                              | Description                                                                                 |
|---------------------------------------|---------------------------------------------------------------------------------------------|
| [`nanmin(a[, axis, out, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.nanmin.html#numpy.nanmin)      | Minimum of an array or along an axis, ignoring `np.nan`.                     |
| [`nanmax(a[, axis, out, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html#numpy.nanmax)      | Maximum of an array or along an axis, ignoring `np.nan`.                 |
| [`ptp(a[, axis, out])`](https://numpy.org/doc/stable/reference/generated/numpy.ptp.html#numpy.ptp)                   | Range of values (max - min) along an axis.                                          |
| [`percentile(a, q[, axis, out, ...])`](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html#numpy.percentile)    | q-th percentile of data along a specified axis.                            |
| [`nanpercentile(a, q[, axis, out, ...])`](https://numpy.org/doc/stable/reference/generated/numpy.nanpercentile.html#numpy.nanpercentile) | q-th percentile of data along a specified axis, ignoring `np.nan`. |

***

Mean (average), standard deviation, and variances

| Function                                          | Description                                                                   |
|---------------------------------------------------|-------------------------------------------------------------------------------|
| [`median(a[, axis, out, overwrite_input, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.median.html#numpy.median) | Median along an (optional) axis.                                  |
| [`average(a[, axis, weights, returned])`](https://numpy.org/doc/stable/reference/generated/numpy.average.html#numpy.average)             | Weighted average along an (optional) axis.                        |
| [`mean(a[, axis, dtype, out, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html#numpy.mean)             | Arithmetic mean along an (optional) axis.                         |
| [`std(a[, axis, dtype, out, ddof, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.std.html#numpy.std)        | Standard deviation along an (optional) axis.                      |
| [`var(a[, axis, dtype, out, ddof, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.var.html#numpy.var)        | Variance along an (optional) axis.                                |
| [`nanmedian(a[, axis, out, overwrite_input, ...])`](https://numpy.org/doc/stable/reference/generated/numpy.nanmedian.html#numpy.nanmedian)   | Median along an (optional) axis, ignoring `np.nan`.             |
| [`nanmean(a[, axis, dtype, out, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html#numpy.nanmean)          | Arithmetic mean along an (optional) axis, ignoring `np.nan`.          |
| [`nanstd(a[, axis, dtype, out, ddof, keepdims])`](https://numpy.org/doc/stable/reference/generated/numpy.nanstd.html#numpy.nanstd)     | Standard deviation along an (optional) axis, while ignoring `np.nan`. |

***

Correlating data (arrays)

| Function                                       | Description                                             |
|------------------------------------------------|---------------------------------------------------------|
| [`corrcoef(x[, y, rowvar, bias, ddof])`](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html#numpy.corrcoef)           | Pearson (product-moment) correlation coefficients. |
| [`correlate(a, v[, mode])`](https://numpy.org/doc/stable/reference/generated/numpy.correlate.html#numpy.correlate)                        | Cross-correlation of two 1-dimensional sequences.       |
| [`cov(m[, y, rowvar, bias, ddof, fweights, ...])`](https://numpy.org/doc/stable/reference/generated/numpy.cov.html#numpy.cov) | Estimate covariance matrix, based on data and weights.   |

***

Generate and plot histograms

| Function                                          | Description                                                                |
|---------------------------------------------------|----------------------------------------------------------------------------|
| [`histogram(a[, bins, range, normed, weights, ...])`](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html#numpy.histogram) | Histogram of a set of data.                                    |
| [`histogram2d(x, y[, bins, range, normed, weights])`](https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html#numpy.histogram2d) | Bi-dimensional histogram of two data samples.                  |
| [`histogramdd(sample[, bins, range, normed, ...])`](https://numpy.org/doc/stable/reference/generated/numpy.histogramdd.html#numpy.histogramdd)   | Multidimensional histogram of some data.                       |
| [`bincount(x[, weights, minlength])`](https://numpy.org/doc/stable/reference/generated/numpy.bincount.html#numpy.bincount)                 | Count number of occurrences of each value in array of non-negative ints.   |
| [`digitize(x, bins[, right])`](https://numpy.org/doc/stable/reference/generated/numpy.digitize.html#numpy.digitize)                        | Indices of the bins to which each value in input array belongs. |

(numpy-matlab)=
## Can *NumPy* do *MATLAB*&reg;?

Are you considering switching to Python after starting softly into programming with *MATLAB&reg;*-like software? There are many reasons for enhancing data analyses with Python and here are some facilitators for previous *MATLAB&reg;* users:

* *MATLAB&reg;* matrices can be loaded and saved with [`scipy.io.loadmat(matrix-file-name)`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html#scipy.io.loadmat) (use `import scipy`).
* *NumPy*'s `np.array` replaces *MATLAB&reg;*'s matrix notation (even though there is the historic, deprecated *NumPy* data type `np.matrix`).
* Import many *MATLAB&reg;* features from `np.matlib` (e.g., `from numpy.matlib import rand, zeros, ones, empty, eye)` or more generally `import numpy.matlib as M`).
* Find the *NumPy* equivalent of many *MATLAB&reg;* function in the [*NumPy* documentation](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html#table-of-rough-matlab-numpy-equivalents).
* To emulate *MATLAB&reg;*'s plot functions use the `pylab` package and import it as `from pylab import *`. <br>&#9888; This overwrites all other (standard) definitions of the `plot()` function and `array()` objects. So this usage is deprecated. [Read the plotting section](pyplot) for comprehensive plotting instructions with *Python*.

*MATLAB&reg; is a registered trademark of The MathWorks.*

```{admonition} Exercise
Practice *numpy* and *csv* file handling in the {ref}`reservoir design exercise <ex-seq-peak>`.
```

(pandas)=
# Pandas

*pandas* is a powerful library for data analyses and manipulation with Python. It can handle *NumPy* arrays, and both packages jointly represent a powerful data processing engine. The power of *pandas* lies in processing data frames, data labeling (e.g., workbook-like column names), and flexible file handling functions (e.g., the built-in `read_csv(csv-file)` function). While *NumPy* arrays enable calculations with multidimensional arrays (beyond 2-dimensional tables) and low memory consumption, *pandas* `DataFrame`s efficiently process and label tabular data with more than ~100,000 rows. Because of its labelling capacity, *pandas* also finds broad application in machine learning. In summary, *pandas*' functionality builds on top of *NumPy* and both libraries are maintained by the [*SciPy*](https://www.scipy.org/) (*Scientific computing tools for Python*) community that also produces `matplotlib` (see the {ref}`plotting section <matplotlib>`) and *IPython* (*Jupyter*'s *Python* kernel).

```{admonition} Watch the pandas section on YouTube
:class: tip, dropdown
<iframe width="701" height="394" src="https://www.youtube-nocookie.com/embed/ruB-r-0Vyjc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<p>Watch this section as a video on the <a href="https://www.youtube.com/@hydroinformatics">@hydroinformatics channel on YouTube</a>.</p>
```

## Installation

*pandas* can be installed through *Anaconda* ({ref}`recall instructions <install-pckg>`) and the developers recommend using a scientific Python distribution (*Anaconda*) with [*SciPy Stack*](https://scipy.org/install/).

The provided *Anaconda* [environment.yml (`flussenv`)](https://raw.githubusercontent.com/Ecohydraulics/flusstools-pckg/main/environment.yml) already includes *pandas* (more information in the {ref}`installation <conda-env>` section). Similarly, Linux users will have *pandas* installed in a virtual environment (e.g., `vflussenv`) with *pip* (recall {ref}`pip-installing flusstools <pip-quick>`). Otherwise, to install *pandas* in any other *conda* environment, open *Anaconda Prompt* (*Start* > type *Anaconda Prompt*) and type:

```python
conda activate ENVIRONMENT-NAME
conda install pandas
```

To pip-install *pandas* in any other virtual environment tap:

```python
pip install pandas
```

## Usage

*pandas* standard import alias is `pd`: `import pandas as pd`. The following sections provide an overview of basic *pandas* functions and many more features are documented in the [developer's docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html).

## Data Frames & Series
The below code block illustrates one way to create a *pandas* data frame (`pd.DataFrame`), one of *pandas* core objects. Note the difference between a 1-dimensional series `pd.Series` (corresponds to a one-column data frame), and an n-dimensional data frame with **row (=index)** and column names. The default row names number rows starting from 0 (unlike Office software that starts at row no. 1), without column names. Column names can be initially defined as a {ref}`list <list>` and replaced with a {ref}`dictionary <dict>` that maps the initial list entries to new names.

In [19]:
import pandas as pd

print("A 1-column pd.DataFrame:\n"+ str(pd.Series([3, 4, np.nan])))  # a simple pandas data frame with one column

row_names = np.arange(1, 4, 1)
wb_like_df = pd.DataFrame(np.random.randn(len(row_names), 3), 
                          index=row_names, columns=['A', 'B', 'C'])
print("\nThis is a workbook-like (row and column names) data frame:\n" + str(wb_like_df))
print("\nRename column names with dictionary:\n" + str(wb_like_df.rename(
        columns={'A': 'Series 1', 'B': 'Series 2', 'C': 'Series 3'})))
print("\nTranspose the data frame:\n" + str(wb_like_df.T))

A 1-column pd.DataFrame:
0    3.0
1    4.0
2    NaN
dtype: float64

This is a workbook-like (row and column names) data frame:
          A         B         C
1 -0.374896  1.510560  0.164615
2  0.171686 -0.668994 -1.850155
3 -0.521211  1.688967 -0.653523

Rename column names with dictionary:
   Series 1  Series 2  Series 3
1 -0.374896  1.510560  0.164615
2  0.171686 -0.668994 -1.850155
3 -0.521211  1.688967 -0.653523

Transpose the data frame:
          1         2         3
A -0.374896  0.171686 -0.521211
B  1.510560 -0.668994  1.688967
C  0.164615 -1.850155 -0.653523


A *pandas* `DataFrame` object can also be created from a {ref}`dictionary <dict>`, where the dictionary keys define column names and the dictionary values constitute the data of every column:

In [20]:
df = pd.DataFrame({'Flow depth': pd.Series(np.random.uniform(low=0.1, high=0.3, size=(4,)), dtype='float32'),
                   'Sediment': ["yes", "no", "yes", "no"],
                   'Flow regime': pd.Categorical(["fluvial", "fluvial", "supercritical", "critical"]),
                   'Water': "Always there"})
print("A dictionary-built data frame:\n" + str(df))
print("\nFrame data types:\n" + str(df.dtypes))

A dictionary-built data frame:
   Flow depth Sediment    Flow regime         Water
0    0.236444      yes        fluvial  Always there
1    0.212434       no        fluvial  Always there
2    0.121081      yes  supercritical  Always there
3    0.290556       no       critical  Always there

Frame data types:
Flow depth      float32
Sediment            str
Flow regime    category
Water               str
dtype: object


Built-in attributes and methods of a *pandas* `DataFrame` enable easy access to the top (head) and the bottom of a data frame and many more object characteristics (recall: use `dir(dict_df)` or [read the developer's docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html)):

In [21]:
print("Head of the dictionary-based dataframe (first two rows):\n" + str(df.head(2)))
print("\nEnd (tail) of the dictionary-based dataframe (last row):\n" + str(df.tail(1)))

Head of the dictionary-based dataframe (first two rows):
   Flow depth Sediment Flow regime         Water
0    0.236444      yes     fluvial  Always there
1    0.212434       no     fluvial  Always there

End (tail) of the dictionary-based dataframe (last row):
   Flow depth Sediment Flow regime         Water
3    0.290556       no    critical  Always there


(exp-Froude)=
## Example: Create a `pandas.DataFrame` of Froude Numbers

In hydraulics, the {term}`Froude number` $Fr$ characterizes the flow regime as *"fluvial"* (*Fr<1*), *"critical"* (*Fr=1*), or *"super-critical"* (*Fr>1*). The precision of measurement devices in physical flume experiments makes the exact determination of the *critical* moment a challenge and forces researchers to apply an interval around 1, rather than the exact value of `1.0`:

| ***Fr*** | (0.00, 0.95( | (0.95, 1.00(           | (1.00)   | )1.00, 1.05)           | )1.05, inf(    |
|----------|--------------|------------------------|----------|------------------------|----------------|
| *Flow*   | fluvial      | near-critical (slow) | critical | near-critical (fast) | super-critical |

`pd.DataFrame( ... )` objects are a convenient way to classify and store flume experiment data:

In [1]:
def classify_froude(fr):
  if fr < 0.95:
	  return "fluvial"
  if fr < 1.0:
	  return "near-critical (slow)"
  if fr == 1.0:
	  return "critical"
  if fr <= 1.05:
	  return "near-critical (fast)"
  return "super-critical"

Fr_measured = np.random.uniform(low=0.01, high=2.00, size=10)
Fr_classified = [classify_froude(fr) for fr in Fr_measured]
obs_df = pd.DataFrame({"measured": Fr_measured, "flow regime": Fr_classified})
print(obs_df)


NameError: name 'np' is not defined

## Append Data to a `pandas.DataFrame`

Avoid repeatedly inserting rows into a DataFrame. Collect new records first and construct a DataFrame once, or concatenate batches with `pd.concat()`. Assigning a complete column is direct and efficient.

The following code block illustrates both adding a row and a column to an existing *pandas* data frame.

In [23]:
import random

new_rows = pd.DataFrame({
  "measured": [0.996],
  "flow regime": ["near-critical (slow)"],
})
obs_df = pd.concat([obs_df, new_rows], ignore_index=True)
obs_df["with sediment"] = [bool(random.getrandbits(1)) for _ in range(len(obs_df))]
print(obs_df.tail(3))


    measured           flow regime  with sediment
8   1.541139        super-critical           True
9   0.189163               fluvial          False
10  0.996000  near-critical (slow)          False


## NumPy Arrays and pandas Data Frames
 
A NumPy array has one data type (`dtype`), while a pandas DataFrame can use a different dtype for each column. `DataFrame.to_numpy()` selects a common dtype for the resulting array and may require type coercion or a copy, depending on the DataFrame's column dtypes. DataFrame index and column labels are not included in the resulting array. If one column of the *pandas* `DataFrame` is non-numeric, the conversion involves copying the object, which then causes high computational costs. Note that the *index* and *column* labels of a *pandas* `DataFrame` are lost in the conversion from `pd.DataFrame` to `np.ndarray`.

In [24]:
print(obs_df.to_numpy())

[[0.7228199423430681 'fluvial' True]
 [1.0994432843154105 'super-critical' True]
 [0.8865704358418128 'fluvial' False]
 [0.8490886765821513 'fluvial' True]
 [1.1750423214539258 'super-critical' True]
 [0.086024140985809 'fluvial' True]
 [1.1575177959070637 'super-critical' True]
 [1.6067571441117197 'super-critical' False]
 [1.5411388862372846 'super-critical' True]
 [0.18916310404617928 'fluvial' False]
 [0.996 'near-critical (slow)' False]]


## Access Data Frames Entries

Elements of data frames are accessible by the column and row label (`df.loc[index=row, column-label]`) or number (`df.iloc`):

In [25]:
print("Label localization results in: " + str(df.loc[2, "Flow depth"]))
print("Same result with integer grid location: " + str(df.iloc[2, 0]))

Label localization results in: 0.12108062
Same result with integer grid location: 0.12108062


(pd-reshape)=
## Reshape Data Frames

Single or multiple rows (indices) and columns can be extracted from and combined into new or existing `DataFrame` objects:

In [26]:
print(pd.DataFrame([df["Flow depth"], df["Sediment"]]))

                   0         1         2         3
Flow depth  0.236444  0.212434  0.121081  0.290556
Sediment         yes        no       yes        no


The `df.stack()` method pivots the columns of a data frame, which is a powerful tool to classify data that can take different dimensions (e.g., the volume and weight of 1 m<sup>3</sup> water - read more about the [stack method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html#pandas.DataFrame.stack)). 

In [27]:
print(df.stack()[0])
df.unstack()  # unstack data frame

Flow depth         0.236444
Sediment                yes
Flow regime         fluvial
Water          Always there
dtype: object


Flow depth   0         0.236444
             1         0.212434
             2         0.121081
             3         0.290556
Sediment     0              yes
             1               no
             2              yes
             3               no
Flow regime  0          fluvial
             1          fluvial
             2    supercritical
             3         critical
Water        0     Always there
             1     Always there
             2     Always there
             3     Always there
dtype: object

Big datasets often contain large amounts of data with many labels, but we are often only interested in a small subset of the data. To this end, data frame subsets can be created with `df.pivot(index, columns, **values)` ([Pivot method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html#pandas.DataFrame.pivot)):

In [28]:
print("Pivot table for \'Flow regime\':\n" + str(df.pivot(index="Sediment", columns="Flow depth")["Flow regime"]))
print("\nPivot table for \'Water\':\n" + str(df.pivot(index="Sediment", columns="Flow depth")["Water"]))

Pivot table for 'Flow regime':
Flow depth       0.121081 0.212434 0.236444  0.290556
Sediment                                             
no                    NaN  fluvial      NaN  critical
yes         supercritical      NaN  fluvial       NaN

Pivot table for 'Water':
Flow depth      0.121081      0.212434      0.236444      0.290556
Sediment                                                          
no                   NaN  Always there           NaN  Always there
yes         Always there           NaN  Always there           NaN


In addition, `df.pivot_table(index, columns, values, aggfunc)` ([Pivot table function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot_table.html#pandas.DataFrame.pivot_table)) enables inline Office-like function application to one or more rows and/or columns.

In [29]:
print("\'mean\' for \'Flow depth\':\n" + str(df.pivot_table(index="Sediment", columns="Flow regime", values="Flow depth", aggfunc=np.mean)))

'mean' for 'Flow depth':
Flow regime  critical   fluvial  supercritical
Sediment                                      
no           0.290556  0.212434            NaN
yes               NaN  0.236444       0.121081


Read more about reshaping and pivoting data frames in the [developer's docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html).

(pd-files)=
## File Handling (*csv*, Workbooks, and More) 

*pandas* can read from and write to many data file types, which makes it extremely powerful for analyzing any data. The following table summarizes the most important file types for numerical hydraulic, morphodynamic, and fluvial landscape analyses, and more file type handlers can be found at the [developer's docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

|  File type                                                                  |  *pandas* read                                                                                         |  *pandas* write                                                                                       | Usage example                                                                                           |
|-----------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------|
|  CSV |  [`read_csv`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-csv-table)       |  [`to_csv`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-store-in-csv)          | Reading from data loggers (e.g., discharge, flow depth)    |
|  Google BigQuery  |  [`read_gbq`](https://en.wikipedia.org/wiki/BigQuery)|  [`to_gbq`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-bigquery)              | Analyze social media   |
|  JSON |  [`read_json`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-json-reader)         |  [`to_json`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-json-writer)          | Manipulate {ref}`chpt-basement` model files    |
|  HTML |  [`read_html`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-read-html)           |  [`to_html`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-html)                 | Process  web site data        |
|  [HDF5 Format](https://support.hdfgroup.org/HDF5/doc1.6/UG/08_TheFile.html) |  [`read_hdf`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-hdf5)                 |  [`to_hdf`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-hdf5)                  | Analyze {ref}`chpt-basement` or [HEC-RAS](https://www.mdpi.com/2073-4441/10/10/1382) output files |
|  Python Pickle Format |  [`read_pickle`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-pickle)            |  [`to_pickle`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-pickle)     | Cache memory dump       |
|  SQL  |  [`read_sql`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-sql)     |  [`to_sql`](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-sql)  | Retrieve and write data to SQL data bases    |
| Workbooks (Excel / OpenDocument) | `read_excel` | `to_excel` | Exchange tabular data with spreadsheet software; supported formats and required engines depend on the file extension. |


The following code block illustrates how the above produced *data/modified-data.csv* file can be loaded and saved to a workbook with *pandas*. *pandas* uses [openpyxl](https://openpyxl.readthedocs.io) by default, but this usage varies depending on the workbook file type (e.g., `.ods`, `.xls`, and `xlsb` build on other packages - [read more about the `engine` keyword](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html)).

In [30]:
measurement_data = pd.read_csv("data/modified-data.csv", sep=",", header=None, names=["Test 1", "Test 2", "Test 3", "Test 4"])
print("Header of data/modified-data.csv:\n" + str(measurement_data.head(3)))
measurement_data.to_excel("data/modified-data-wb.xlsx", sheet_name="2025-01-01 Tests")

Header of data/modified-data.csv:
   Test 1 Test 2 Test 3 Test 4
0     2.0    4.0    nan    2.0
1     NaN    nan    1.0    2.0
2     2.0    3.0    2.0    3.0


```{figure} ../img/py-pandas-xlsx-out.png
:alt: python pandas excel output
:name: py-pandas-xlsx-out

The xlsx output file produced with pandas.
```

```{note}
pandas infers each column's dtype from its values. A column containing both numbers and text commonly has an `object` or string-related dtype, but an Excel writer can still store numeric and text cells in the same worksheet column. Use `np.nan` or another supported missing-value marker instead of the literal string `"nan"` when missing numeric data should remain distinguishable from text.
```

A *pandas* `ExcelWriter` object can be created to write multiple `pd.DataFrame` objects to a workbook, on one or more sheets. Here is an example, where the non-numeric `"nan"` strings are replaced in `measurement_data` with `np.nan` to yield a purely numeric data frame in two steps (`# (1)` and `# (2)`):

In [31]:
measurement_data = measurement_data.replace("nan", np.nan, regex=True)  # (1) replace "nan" with np.nan
measurement_data = measurement_data.apply(pd.to_numeric)  # (2) convert all data to numeric

# write workbook with pd ExcelWriter object
with pd.ExcelWriter("data/modified-data-wb-EW.xlsx") as writer:
    measurement_data.to_excel(writer, sheet_name="2025-01-01 Tests")
    df.to_excel(writer, sheet_name="pandas example")

```{figure} ../img/py-pandas-xlsx-out2.png
:alt: python pandas excel xlsx with nan
:name: py-pandas-xlsx-out2

The xlsx file with nan strings.
```

## Categorical Data

*string* variables that represent statistically relevant categories are the baseline for data classification and statistics. *pandas* provides the special data type of `dtype="category"` to facilitate statistical analyses.

In the above {ref}`Froude-number example <exp-Froude>`, we used five categories to classify the flow regime as a function of the *Froude number*, which can serve as categories. This is useful, for instance, when no water was flowing or when a sensor broke in an experiment and we want to categorize our measurements to filter valid tests only:

In [32]:
flow_regimes = ["fluvial", "near-critical (slow)", "critical", "near-critical (fast)", "super-critical"]
observation_examples = ["fluvial", "dry", "critical", "near-critical (slow)", "measurement error"]
Fr_cat = pd.Categorical(observation_examples, categories=flow_regimes, ordered=False)
print(pd.Series(Fr_cat))

0                 fluvial
1                     NaN
2                critical
3    near-critical (slow)
4                     NaN
dtype: category
Categories (5, str): ['fluvial', 'near-critical (slow)', 'critical', 'near-critical (fast)', 'super-critical']


/tmp/ipykernel_16649/2029032689.py:3: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  Fr_cat = pd.Categorical(observation_examples, categories=flow_regimes, ordered=False)


## Data Frame Statistics

*pandas* has efficient routines to perform workbook-like row or column sorting (e.g., [`df.sort_index()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html) or [`df.sort_values()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html)), and enables the fast calculation of data frame statistics with `df.describe()`, where 25%, 50%, and 75% represent the *i-th* percentiles:

In [33]:
measurement_data.describe()

,Test 1,Test 2,Test 3,Test 4
count,14.000000,15.000000,10.000000,16.000000
mean,2.785714,3.266667,2.900000,3.062500
std,1.423893,1.032796,1.197219,1.611159
min,1.000000,1.000000,1.000000,1.000000
25%,2.000000,3.000000,2.000000,2.000000
50%,2.500000,3.000000,3.000000,3.000000
75%,4.000000,4.000000,3.750000,4.000000
max,5.000000,5.000000,5.000000,8.000000


Statistical *pandas* data frame methods overlap with *NumPy* methods and include:

* `df.abs()` calculates absolute values
* `df.cumprod()` calculates the cumulative product
* `df.cumsum()` calculates the cumulative sum
* `df.count()` counts the number of non-null observations
* `df.max()` calculates the maximum value
* `df.mean()` calculates the mean (average)
* `df.min()` calculates the minimum value
* `df.mode()` calculates the mode
* `df.prod()` calculates the product
* `df.std()` calculates the standard deviation
* `df.sum()` calculates the sum



In [34]:
print("Mean:\n" + str(measurement_data.mean()))
print("Median:\n" + str(measurement_data.median()))
print("Standard deviation:\n" + str(measurement_data.std()))

Mean:
Test 1    2.785714
Test 2    3.266667
Test 3    2.900000
Test 4    3.062500
dtype: float64
Median:
Test 1    2.5
Test 2    3.0
Test 3    3.0
Test 4    3.0
dtype: float64
Standard deviation:
Test 1    1.423893
Test 2    1.032796
Test 3    1.197219
Test 4    1.611159
dtype: float64


```{tip}
*pandas* has many more built-in functionalities, for example, to plot histograms or any data using the `matplotlib` library, and machine learning.
```

## Apply Custom (Own) Functions to Data Frames

*pandas* data frames have a built-in `apply(fun)` method that enables applying a custom function to (parts of) a `pd.DataFrame` object. The following code block borrows from the `feet_to_meter` function from the {ref}`functions <kwargs>` chapter ([download converter.py](https://raw.githubusercontent.com/hydro-informatics/jupyter-python-course/main/fun/converter.py)).  The *pandas* docs provide more information about the [pandas.apply](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.apply.html) method.

In [35]:
from fun.converter import feet_to_meter

# create data frame with random integers
df = pd.DataFrame({"Feet": np.random.randint(0, 100, size=6),
                   "Meters": np.ones(6) * np.nan})

# apply feet_to_meter to the Meters columns of the data frame
df["Meters"] = df["Feet"].apply(feet_to_meter)

print(df)

   Feet   Meters
0    18   5.4864
1    62  18.8976
2    53  16.1544
3    95  28.9560
4    61  18.5928
5    59  17.9832


# Dates and Time

*pandas* involves methods for calculations and labeling with date and time values through [`pd.Timestamp`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.html), which converts date-time-like strings into timestamps or creates timestamps from keyword arguments:

In [36]:
print(pd.Timestamp('2025-01-01T12'))
print(pd.Timestamp(year=2025, month=1, day=1, hour=12))
print(pd.Timestamp(2025, 1, 1, 12))

2025-01-01 12:00:00
2025-01-01 12:00:00
2025-01-01 12:00:00


The expression `pd.Timestamp(2025, 1, 1, 12)` mimics the powerful `datetime.datetime` *API* (Application Programming Interface) of the `datetime` Python library, which provides sophisticated methods for handling time-dependent values. While *pandas*' built-in timestamps are convenient for creating time series within `pd.DataFrame` objects and workbook-like tables, `datetime` is one of the best solutions for time-dependent calculations in Python. `datetime` is available by default (i.e., it must not be *conda* or *pip*-installed) and is efficiently applicable, for example, to data that were collected over several years including leap years. The `datetime` package comes with many attributes and methods, which are documented in detail in the [Python docs](https://docs.python.org/3/library/datetime.html).

The standard usage is:

In [37]:
import datetime as dt
start_date = dt.datetime(2024, 2, 25, 22, 30, 0)
end_date = dt.datetime(year=2024, month=3, day=2, hour=2, minute=15, second=30)
print("Datetime variables can be subtracted:\n" + str(end_date - start_date))
print("The result is a %s object." % type(end_date - start_date))

Datetime variables can be subtracted:
5 days, 3:45:30
The result is a <class 'datetime.timedelta'> object.


`dt.timedelta` objects can also be separately defined:

In [38]:
time_diff = dt.timedelta(days=0, seconds=0, microseconds=0, milliseconds=0, minutes=0, hours=23, weeks=0)
act_time = start_date
print("Iterate from start to end date with stepsize=time_diff:")
while act_time <= end_date:
    print(act_time.strftime("%Y-%m(%h)-%d, %H:%M:%S"))
    act_time += time_diff

Iterate from start to end date with stepsize=time_diff:
2024-02(Feb)-25, 22:30:00
2024-02(Feb)-26, 21:30:00
2024-02(Feb)-27, 20:30:00
2024-02(Feb)-28, 19:30:00
2024-02(Feb)-29, 18:30:00
2024-03(Mar)-01, 17:30:00


That is all for the introduction to data and file handling. Though there is much more to data processing than shown in this chapter and the next other chapters of this eBook will occasionally feature more tools.

```{admonition} Exercise
Practice *pandas* and its *csv* file handling routines, as well as basic date-time handling in the {ref}`flood return period calculation exercise <ex-floods>`.
```

# Learning Success Check-up

Take the [learning success test for this Jupyter notebook](https://forms.gle/V2EiNFEiszL38Aov8).

````{admonition} Unfold QR Code
:class: tip, dropdown

```{image} ../img/qr-codes/gle-pynum.png
```
````